In [22]:
import pandas as pd
import numpy as np

In [16]:
ICD10 = pd.read_csv('ICD10.csv')

In [19]:
ICD10

,CODE,SHORT DESCRIPTION (VALID ICD-10 FY2023),LONG DESCRIPTION (VALID ICD-10 FY2023),NF EXCL,Unnamed: 4
0,A000,"Cholera due to Vibrio cholerae 01, biovar chol...","Cholera due to Vibrio cholerae 01, biovar chol...",NaN,NaN
1,A001,"Cholera due to Vibrio cholerae 01, biovar eltor","Cholera due to Vibrio cholerae 01, biovar eltor",NaN,NaN
2,A009,"Cholera, unspecified","Cholera, unspecified",NaN,NaN
3,A0100,"Typhoid fever, unspecified","Typhoid fever, unspecified",NaN,NaN
4,A0101,Typhoid meningitis,Typhoid meningitis,NaN,NaN
...,...,...,...,...,...
72831,Y990,Civilian activity done for income or pay,Civilian activity done for income or pay,Y,NaN
72832,Y991,Military activity,Military activity,Y,NaN
72833,Y992,Volunteer activity,Volunteer activity,Y,NaN
72834,Y998,Other external cause status,Other external cause status,Y,NaN
72835,Y999,Unspecified external cause status,Unspecified external cause status,Y,NaN

In [20]:
ICD10.columns = ['code','desc','long_desc','nf_excl','unamed']

In [51]:
def find_ICD10(key):
    results_df = pd.DataFrame()
    for diseases in ICD10.long_desc:
        if key in str(diseases):
            code = ICD10.iloc[np.where(ICD10.long_desc==diseases)].code
            keep = ICD10.iloc[np.where(ICD10.long_desc==diseases)].iloc[:,0:3]
            #print(keep)
            results_df = pd.concat([results_df,keep])
    return results_df.copy()

In [56]:
find_ICD10('facial pain')

      code                  desc             long_desc
5221  G501  Atypical facial pain  Atypical facial pain

In [61]:
def find_ICD10(*keys):
    results_df = pd.DataFrame()
    for diseases in ICD10.long_desc:
        if all(key in str(diseases) for key in keys):
            code = ICD10.iloc[np.where(ICD10.long_desc == diseases)].code
            keep = ICD10.iloc[np.where(ICD10.long_desc == diseases)].iloc[:, 0:3]
            results_df = pd.concat([results_df, keep])
    return results_df.copy()

In [68]:
find_ICD10('pain','leg')

,code,desc,long_desc
9609,I70221,Athscl native arteries of extremities w rest p...,Atherosclerosis of native arteries of extremit...
9610,I70222,Athscl native arteries of extremities w rest p...,Atherosclerosis of native arteries of extremit...
9611,I70223,"Athscl native arteries of extrm w rest pain, b...",Atherosclerosis of native arteries of extremit...
9649,I70321,Athscl unsp type bypass of the extrm w rest pa...,Atherosclerosis of unspecified type of bypass ...
9650,I70322,Athscl unsp type bypass of the extrm w rest pa...,Atherosclerosis of unspecified type of bypass ...
9651,I70323,Athscl unsp type bypass of the extrm w rest pa...,Atherosclerosis of unspecified type of bypass ...
9689,I70421,Athscl autol vein bypass of the extrm w rest p...,Atherosclerosis of autologous vein bypass graf...
9690,I70422,Athscl autol vein bypass of the extrm w rest p...,Atherosclerosis of autologous vein bypass graf...
9691,I70423,Athscl autol vein bypass of the extrm w rest p...,Atherosclerosis of autologous vein bypass graf...
9729,I70521,Athscl nonaut bio bypass of the extrm w rest p...,Atherosclerosis of nonautologous biological by...
9730,I70522,Athscl nonaut bio bypass of the extrm w rest p...,Atherosclerosis of nonautologous biological by...
9731,I70523,Athscl nonaut bio bypass of the extrm w rest p...,Atherosclerosis of nonautologous biological by...
9769,I70621,Athscl nonbiol bypass of the extrm w rest pain...,Atherosclerosis of nonbiological bypass graft(...
9770,I70622,Athscl nonbiol bypass of the extrm w rest pain...,Atherosclerosis of nonbiological bypass graft(...
9771,I70623,Athscl nonbiol bypass of the extrm w rest pain...,Atherosclerosis of nonbiological bypass graft(...
9809,I70721,Athscl type of bypass of the extrm w rest pain...,Atherosclerosis of other type of bypass graft(...
9810,I70722,Athscl type of bypass of the extrm w rest pain...,Atherosclerosis of other type of bypass graft(...
9811,I70723,Athscl type of bypass of the extrm w rest pain...,Atherosclerosis of other type of bypass graft(...